management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,startup

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${PG_STORE_DB_USER:pg}
    password: ${PG_STORE_DB_PASSWORD:pg}
    url: jdbc:postgresql://${PG_STORE_HOST:localhost}:${PG_STORE_PORT:5432}/${PG_STORE_DB_NAME:pg_store}
  jpa:
    hibernate:
      ddl-auto: update # temporary for easy development
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED # fix of hibernate bug