logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,startup
  tracing:
    sampling:
      probability: 1.0
server:
  port: 8081
spring:
  application:
    name: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${MVP_USER_DB_USER:mvp}
    password: ${MVP_USER_DB_PASSWORD:mvp}
    url: jdbc:postgresql://${MVP_USER_HOST:localhost}:${MVP_USER_PORT:5432}/${MVP_USER_DB_NAME:mvp_party}
  jpa:
    hibernate:
      ddl-auto: update # temporary for easy development
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      jakarta:
        persistence:
          sharedCache:
            mode: UNSPECIFIED # fix of hibernate bug